{% set name = "pytest-aiohttp" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 147de8cb164f3fc9d7196967f109ab3c0b93ea3463ab50631e56438eab7b5adc

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=51.0
    - setuptools_scm >=6.2
  run:
    - python >={{ python_min }}
    - pytest >=6.1.0
    - aiohttp >=3.8.1
    - pytest-asyncio >=0.17.2

test:
  requires:
    - python {{ python_min }}
  imports:
    - pytest_aiohttp

about:
  home: https://github.com/aio-libs/pytest-aiohttp
  dev_url: https://github.com/aio-libs/pytest-aiohttp
  doc_url: https://docs.aiohttp.org/en/stable/testing.html
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: pytest plugin for aiohttp support

extra:
  recipe-maintainers:
    - klauer
    - asmeurer
