{% set name = "pytest-aiohttp" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 56239a3e0abc393d9037995b2aa04a024c5e172e17046f2ef831a293fa13ace9

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4
    - pytest
    - aiohttp >=2.3.5

test:
  imports:
    - pytest_aiohttp

about:
  home: https://github.com/aio-libs/pytest-aiohttp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: pytest plugin for aiohttp support

  dev_url: https://github.com/aio-libs/pytest-aiohttp

extra:
  recipe-maintainers:
    - asmeurer
