{% set name = "pytest-aiohttp" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 39ff3a0d15484c01d1436cbedad575c6eafbf0f57cdf76fb94994c97b5b8c5a4

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  noarch: python

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4
    - pytest
    - aiohttp >=2.3.5

test:
  imports:
    - pytest_aiohttp

about:
  home: https://github.com/aio-libs/pytest-aiohttp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'pytest plugin for aiohttp support'

  dev_url: https://github.com/aio-libs/pytest-aiohttp

extra:
  recipe-maintainers:
    - klauer
    - asmeurer
